config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles

  resources :authors, excpet: [:new, :destroy]
  get '/register', to: 'authors#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  default_scope {order(created_at: :desc)}
end

app/models/author.rb
class Author < ActiveRecord::Base
  before_save :email_downcase
  validates :name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}

  has_secure_password

  private
    def email_downcase
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user, :log_in

  def current_user
    @current_user ||= Author.find(session[:author_id]) if session[:author_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    session[:author_id] = user.id
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  before_filter :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show   
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render :new
    end
  end

  def edit
  end

  def update   
    if @article.update(article_params)
      flash[:success] = "Article has been updated"
      redirect_to @article
    else
      flash.now[:danger] = "Article has not been updated"
      render :edit
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been deleted"
      render :show
    end   
  end

  private

    def article_params
      params.require(:article).permit(:title, :body)
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def authenticate_user
      if !logged_in?
        flash[:danger] = "Must be logged in to preform this action"
        redirect_to :back
      end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Welcome to Blog App!"
      log_in(@author)
      redirect_to articles_path
    else
      flash.now[:danger] = "Signup Failed"
      render :new
    end

  end

  private
    def author_params
      params.require(:author).permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

  def create
    author = Author.find_by(email: params[:session][:email])
    if author and author.authenticate(params[:session][:password])
      flash[:success] = "Your logged in!"
      #Log in User
      log_in(author)
      redirect_to articles_path
    else
      flash.now[:danger] = "Password and email do not match"
      render :new
    end
  end

  def destroy
    session[:author_id] = nil
    @current_user = nil
    flash[:success] = "You are logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/articles/_article.html.erb
<div class="well well-lg">

  <div class="article-title">
    <%= link_to article.title, article_path(article) %>
  </div>

  <div class="article-body">
    <%= article.body %>
  </div>

</div>

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, html: {class:"form-horizontal"}) do |f| -%>
      <%= render partial: "shared/errors", object: @article.errors %>

      <div class="form-group">

        <div class="col-md-1">
          <%= f.label :title,"Title", class: "control-label" %>
        </div>

        <div class="col-md-11">
          <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
        </div>

      </div>

      <div class="form-group">

        <div class="control-label col-md-1">
          <%= f.label :body, "Body", class: "control-label" %>
        </div>

        <div class="col-md-11">
          <%= f.text_area :body, rows: 10, class: "form-control",placeholder: "Write article here" %>
        </div>

      </div>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h3 class="text-center">Editing an Article</h3>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing All Articles</h1>

<%= link_to "New Article", new_article_path, class: "btn btn-success btn-large", id: "new-article-btn" %>

<%= render partial: "article", collection: @articles %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding a New Article</h3>

<%= render 'form' %>

app/views/articles/show.html.erb
<article class="detail-article">

  <h1 class="article-detail-title"><%= @article.title %></h1>
  <div class="glyphicon glyphicon-calendar" id="article-date">
    <%= @article.created_at.strftime("%b %d, %Y") %>
  </div>
  
  <div class="article-body">
    <%= @article.body %>
  </div>
  <hr>
  <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary btn-lg" %>
  <%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger btn-lg btn-space@" %>
</article>

app/views/authors/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <%= form_for @author do |f| -%>
    <%= render partial: "shared/errors", object: @author.errors %>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name,class:"form-control" %>

      <%= f.label :email, "Email" %>
      <%= f.email_field :email,class:'form-control' %>

      <%= f.label :password, "Password" %>
      <%= f.password_field :password,class:'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation,class:"form-control" %>

      <%= f.submit @author.new_record? ? "Register":"Edit Profile",class:"btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="container-fluid">
  <% flash.each do |name,msg| %>
  <div class='alert alert-dismissible alert-<%= "#{name}" %>'>
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= content_tag(:div, msg, :id => "flash_#{name}") if msg.is_a?(String) %>
  </div>
  <% end  %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed top">  
  <div class="container-fluid">
    <div class="narbar-header">
      <button class="navbar-toggle" type ="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog App", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Authors", authors_path %></li>
      </ul>
          <ul class="nav navbar-nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
    </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<%= render 'layouts/flash' %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-8">
      <%= yield %>
    </div>


    <div class="col-md-4">
      <%= yield :sidebar %>
    </div>
  </div>
</div>





</body>
</html>

app/views/shared/_errors.html.erb
<% if errors.any? %>

  <div class="panel panel-danger col-md-offset-1">
    <div class="panel-heading">
      <h2 class="panel-title">
        <%= pluralize(errors.count,"error") %>
            prohibited this article from being saved. 
      </h2>
    </div>

    <div class="panel-body">
      <ul>
        <% errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  </div>
<% end %>